# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: list files
      run: dir
      
    - name: Build with Maven
      run: mvn -B package --file mow/pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: mowitnow
          path: mow\target\mow-0.0.1-SNAPSHOT.jar
